// Generated by gencpp from file learning_communication/MoveResult.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_MOVERESULT_H
#define LEARNING_COMMUNICATION_MESSAGE_MOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_communication
{
template <class ContainerAllocator>
struct MoveResult_
{
  typedef MoveResult_<ContainerAllocator> Type;

  MoveResult_()
    : total_distance(0)  {
    }
  MoveResult_(const ContainerAllocator& _alloc)
    : total_distance(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_distance_type;
  _total_distance_type total_distance;





  typedef boost::shared_ptr< ::learning_communication::MoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_communication::MoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResult_

typedef ::learning_communication::MoveResult_<std::allocator<void> > MoveResult;

typedef boost::shared_ptr< ::learning_communication::MoveResult > MoveResultPtr;
typedef boost::shared_ptr< ::learning_communication::MoveResult const> MoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_communication::MoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_communication::MoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learning_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'learning_communication': ['/home/shawn/catkin_ws/src/learning_communication/msg', '/home/shawn/catkin_ws/devel/share/learning_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::MoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::MoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_communication::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "964934829dcb6ab30c4d12231d0e56ad";
  }

  static const char* value(const ::learning_communication::MoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x964934829dcb6ab3ULL;
  static const uint64_t static_value2 = 0x0c4d12231d0e56adULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_communication::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_communication/MoveResult";
  }

  static const char* value(const ::learning_communication::MoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_communication::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define result\n"
"uint32 total_distance\n"
"\n"
;
  }

  static const char* value(const ::learning_communication::MoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_communication::MoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_communication::MoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_communication::MoveResult_<ContainerAllocator>& v)
  {
    s << indent << "total_distance: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_MOVERESULT_H
