// Generated by gencpp from file learning_communication/Score.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_SCORE_H
#define LEARNING_COMMUNICATION_MESSAGE_SCORE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_communication
{
template <class ContainerAllocator>
struct Score_
{
  typedef Score_<ContainerAllocator> Type;

  Score_()
    : classes()
    , score(0.0)  {
    }
  Score_(const ContainerAllocator& _alloc)
    : classes(_alloc)
    , score(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _classes_type;
  _classes_type classes;

   typedef float _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::learning_communication::Score_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_communication::Score_<ContainerAllocator> const> ConstPtr;

}; // struct Score_

typedef ::learning_communication::Score_<std::allocator<void> > Score;

typedef boost::shared_ptr< ::learning_communication::Score > ScorePtr;
typedef boost::shared_ptr< ::learning_communication::Score const> ScoreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_communication::Score_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_communication::Score_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learning_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'learning_communication': ['/home/shawn/catkin_ws/src/learning_communication/msg', '/home/shawn/catkin_ws/devel/share/learning_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::Score_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_communication::Score_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::Score_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_communication::Score_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::Score_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_communication::Score_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_communication::Score_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c81dd8d900f3622d702e378825806a6";
  }

  static const char* value(const ::learning_communication::Score_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c81dd8d900f3622ULL;
  static const uint64_t static_value2 = 0xd702e378825806a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_communication::Score_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_communication/Score";
  }

  static const char* value(const ::learning_communication::Score_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_communication::Score_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string classes\n"
"float32 score\n"
;
  }

  static const char* value(const ::learning_communication::Score_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_communication::Score_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.classes);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Score_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_communication::Score_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_communication::Score_<ContainerAllocator>& v)
  {
    s << indent << "classes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.classes);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_SCORE_H
