// Auto-generated. Do not edit!

// (in-package learning_communication.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_distance = null;
    }
    else {
      if (initObj.hasOwnProperty('total_distance')) {
        this.total_distance = initObj.total_distance
      }
      else {
        this.total_distance = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveResult
    // Serialize message field [total_distance]
    bufferOffset = _serializer.uint32(obj.total_distance, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveResult
    let len;
    let data = new MoveResult(null);
    // Deserialize message field [total_distance]
    data.total_distance = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learning_communication/MoveResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '964934829dcb6ab30c4d12231d0e56ad';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define result
    uint32 total_distance
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveResult(null);
    if (msg.total_distance !== undefined) {
      resolved.total_distance = msg.total_distance;
    }
    else {
      resolved.total_distance = 0
    }

    return resolved;
    }
};

module.exports = MoveResult;
